services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - database:/usr/src/app/database
    env_file:
      - secret.env
    networks:
      - network
    ports:
      - "8000:8000"
    restart: always

networks:
  network:
    driver: bridge
volumes:
  database:
