services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    expose:
      - 8000
    volumes:
      - database:/usr/src/app/database
    env_file:
      - secret.env
    networks:
      - network
    restart: always

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/cert.pem:/etc/cert.pem
      - ./nginx/key.pem:/etc/key.pem
      - ./nginx/entrypoint.sh:/etc/nginx/entrypoint.sh:ro
    depends_on:
      - app
      - certbot
    networks:
      - network
    entrypoint: [ "/bin/sh", "-c", "/etc/nginx/entrypoint.sh" ]
    restart: always

  certbot:
    ports:
      - "6000:80"
    env_file:
      - secret.env
    volumes:
      - ./nginx/:/etc/nginx/
    build:
      context: ./certbot
      dockerfile: Dockerfile
    networks:
      - network

networks:
  network:
    driver: bridge
volumes:
  database:
