services:
  app:
    build: .
    expose:
      - 8000
    volumes:
      - database:/usr/src/app/database
    env_file:
      - secret.env
    networks:
      - network

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - network

networks:
  network:
    driver: bridge
volumes:
  database:
