services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    expose:
      - 8000
    volumes:
      - database:/usr/src/app/database
    env_file:
      - secret.env
    networks:
      - network
    restart: always

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/cert.pem:/etc/cert.pem
      - ./nginx/key.pem:/etc/key.pem
    depends_on:
      - app
      - certbot
    networks:
      - network
    restart: always

  certbot:
    ports:
      - "6000:80"
    env_file:
      - secret.env
    volumes:
      - ./nginx/:/etc/nginx/
    build:
      context: ./certbot
      dockerfile: Dockerfile
      args:
        DOMAIN_EMAIL: ${DOMAIN_EMAIL}
        DOMAIN_URL: ${DOMAIN_URL}
    networks:
      - network

networks:
  network:
    driver: bridge
volumes:
  database:
